### ISSUE TITLE
menteslibres.net is down

### ISSUE THREAD

**Issue by yookoala** [xiam/to#6]
The server behind the Cloudflare setup of menteslibres.net is down. Now menteslibres.net is constantly displaying a "502 Bad Gateway". Thus `menteslibres.net/gosexy/to` is not installable by `go get` or `go mod`.

If the site is a static site, please consider to move to Github page or other free hosting service so the packges can be installable again. Thanks.

**Comment by xiam** [comment]
Moved to Github! thanks

**Comment by yookoala** [comment]
Both the domain `menteslibres.net` and `www.menteslibres.net` do not resolve to anything right now. I can see you're using Cloudflare as your DNS. Perhaps there is some misconfiguration there.

```
$ dig menteslibres.net

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> menteslibres.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33525
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;menteslibres.net.		IN	A

;; Query time: 219 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Dec 19 14:56:47 HKT 2019
;; MSG SIZE  rcvd: 45

$ dig www.menteslibres.net

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> www.menteslibres.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 59224
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.menteslibres.net.		IN	A

;; Query time: 231 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Dec 19 14:57:06 HKT 2019
;; MSG SIZE  rcvd: 49
```

**Comment by yookoala** [comment]
Some documentation for setting up apex domain (i.e. `menteslibres.net`) on GitHub pages:

* https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain
* https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site
